- name: This playbook is used to zip and upload the code in the s3 bucket
  var:
      ansible_python_interpreter: /usr/bin/python3
  hosts: localhost
  connection: local
  gather_facts: false
 
  tasks:
    - name: Copy the compiled jar to the s3 bucket
      aws_s3:
        bucket: "hellotrupti"
        object: "lambda/hello-lambda.jar"
        src: "target/hello-lambda-function.jar"
        mode: put
        encrypt: no
        region: "ap-south-1"
